"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { organizationClient } from "@/modules/organizations/presentation/api/organizationClient";
import type { OrganizationMemberView } from "@/modules/organizations/presentation/types/organizationViewModels";
import type { Team, TeamMemberRole } from "@/modules/teams/domain/team";

export function OrganizationTeams({ organizationId, organizationMembers, canManage }: Readonly<{ organizationId: string; organizationMembers: ReadonlyArray<OrganizationMemberView>; canManage: boolean }>) {
  const [teams, setTeams] = useState<ReadonlyArray<Team>>([]); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setTeams(await organizationClient.teams(organizationId)); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar as equipes."); } }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); try { await organizationClient.createTeam(organizationId, name); setName(""); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível criar a equipe."); } finally { setBusy(false); } }
  async function addMember(teamId: string, form: HTMLFormElement) { const data = new FormData(form); setBusy(true); try { await organizationClient.addTeamMember(organizationId, teamId, String(data.get("userId")), String(data.get("role")) as TeamMemberRole); form.reset(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível adicionar o membro."); } finally { setBusy(false); } }
  return <section className="space-y-4 border-t border-slate-200 pt-6"><div><h2 className="text-xl font-bold text-slate-950">Equipes e setores</h2><p className="mt-1 text-sm text-slate-600">Organize os colaboradores responsáveis por cada parte dos processos.</p></div>
    {canManage ? <form className="flex flex-col gap-3 border bg-white p-4 sm:flex-row" onSubmit={create}><label className="flex-1 text-sm font-medium">Nome da equipe<input className="mt-1 h-10 w-full border border-slate-300 px-3" maxLength={160} onChange={(event) => setName(event.target.value)} placeholder="Financeiro" required value={name} /></label><button className="self-end bg-brand-600 px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy ? "Salvando..." : "Criar equipe"}</button></form> : null}
    {error ? <p className="border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}
    {teams.length === 0 ? <p className="border border-dashed bg-white p-6 text-center text-sm text-slate-600">Nenhuma equipe cadastrada.</p> : <div className="grid gap-4 lg:grid-cols-2">{teams.map((team) => <article className="border bg-white p-5" key={team.id}><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold">{team.name}</h3><p className="text-sm text-slate-500">{team.members.length} membro(s)</p></div>{canManage ? <button className="text-sm font-semibold text-rose-700" disabled={busy} onClick={async () => { setBusy(true); try { await organizationClient.removeTeam(organizationId, team.id); await load(); } finally { setBusy(false); } }} type="button">Excluir</button> : null}</div>
      <ul className="mt-4 divide-y">{team.members.map((member) => <li className="flex items-center justify-between gap-3 py-3 text-sm" key={member.userId}><div><p className="font-semibold">{member.name}</p><p className="text-slate-500">{member.email}</p></div>{canManage ? <div className="flex items-center gap-2"><select aria-label={`Papel de ${member.name}`} className="h-9 border px-2" disabled={busy} value={member.role} onChange={async (event) => { setBusy(true); try { await organizationClient.changeTeamMemberRole(organizationId, team.id, member.userId, event.target.value as TeamMemberRole); await load(); } finally { setBusy(false); } }}><option value="member">Membro</option><option value="manager">Gestor</option></select><button className="text-rose-700" onClick={async () => { setBusy(true); try { await organizationClient.removeTeamMember(organizationId, team.id, member.userId); await load(); } finally { setBusy(false); } }} type="button">Remover</button></div> : <span className="text-slate-500">{member.role === "manager" ? "Gestor" : "Membro"}</span>}</li>)}</ul>
      {canManage ? <form className="mt-4 grid gap-2 border-t pt-4 sm:grid-cols-[1fr_auto_auto]" onSubmit={(event) => { event.preventDefault(); void addMember(team.id, event.currentTarget); }}><select aria-label={`Adicionar membro em ${team.name}`} className="h-10 border px-2" name="userId" required defaultValue=""><option value="" disabled>Selecione um colaborador</option>{organizationMembers.filter((candidate) => !team.members.some((member) => member.userId === candidate.userId)).map((member) => <option key={member.userId} value={member.userId}>{member.user?.name ?? member.userId}</option>)}</select><select aria-label={`Papel na equipe ${team.name}`} className="h-10 border px-2" defaultValue="member" name="role"><option value="member">Membro</option><option value="manager">Gestor</option></select><button className="bg-slate-900 px-3 py-2 text-sm font-semibold text-white" disabled={busy}>Adicionar</button></form> : null}
    </article>)}</div>}
  </section>;
}
